apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: profilescreener
resources:
  - ../../base
components:
  - ../../components/ollama
patches:
  - path: config-patch.yaml
    target:
      kind: ConfigMap
      name: profilescreener-config
